---
- name: Restart rsyslog
  become: true
  ansible.builtin.service:
    name: rsyslog
    state: restarted
    # Needed to force SysV service manager on Docker for Molecule tests
    use: "{{ ansible_facts['service_mgr'] }}"
  when:
    - ansible_facts['os_family'] != "Darwin"
    - ansible_facts['os_family'] != "Windows"
  listen: restart rsyslog
