---
- name: Restart syslog-ng
  become: true
  ansible.builtin.service:
    name: syslog-ng
    state: restarted
    # Needed to force SysV service manager on Docker for Molecule tests
    use: "{{ ansible_facts['service_mgr'] }}"
  listen: restart syslog-ng
