---
- name: Start consul snapshot on Unix
  become: true
  ansible.builtin.service:
    name: consul_snapshot
    state: started
    enabled: true
    # Needed to force SysV service manager on Docker for Molecule tests
    use: "{{ ansible_facts['service_mgr'] }}"
  when:
    - ansible_facts['os_family'] != "Darwin"
    - ansible_facts['os_family'] != "Windows"
  listen: start snapshot
